import DirectionStrategySummaryPriorityItem
    from "~/ui/components/Modules/Direction/DirectionStrategySummaryPriorityItem/DirectionStrategySummaryPriorityItem";

export default DirectionStrategySummaryPriorityItem