import RecurringActionItemDeleteConfirmationModal
    from "~/ui/components/Dialogs/RecurringActionItemDeleteConfirmationModal/RecurringActionItemDeleteConfirmationModal";

export default RecurringActionItemDeleteConfirmationModal