export enum FormInputType {
  TEXT = 'text',
  DATE = 'date',
  DATETIME = 'datetime',
  TIME = 'time',
  YEAR = 'year',
  MONTHYEAR = 'month_year',
  NUMBER = 'number',
  SELECT = 'select',
  TEL = 'tel',
  EMAIL = 'email',
  COLOR = 'color',
  CHECKBOX = 'checkbox',
  FILE = 'file',
  IMAGE = 'image',
  MONTH = 'month',
  PASSWORD = 'password',
  RADIO = 'radio',
  RANGE = 'range',
  URL = 'url',
  TEXTAREA = 'textarea',
  BUTTONGROUP = 'button_group',
  AUTOCOMPLETE = 'autocomplete'
}
