export interface PlanMemberItem {
    PlanMemberItemID: number,
    PlanMemberID: number,
    PersonID: number,
    IsAdvisorItem: boolean,
    DestinyItemID: number,
    IsAllFamily: boolean,
    Category: string,
    Subcategory: string,
    ItemType: string,
    Title: string,
    Subtitle: string,
    Description: string,
    Content: string,
    Author: string,
    ImageUrl: string,
    StartDate: string,
    Location: string,
    Url: string,
    Duration: string,
    UserId: number | undefined,
    IsComplete: boolean,
    CompletedDate: string
}