/**
 * LifeMapWebAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface RegistrationCode { 
    RegistrationCodeID?: number;
    RegistrationCode: string;
    Issued?: boolean;
    IssuedTo: string;
    IssuedDate?: Date;
    Claimed?: boolean;
    ClaimedDate?: Date;
    EmailAddress: string;
}
